INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION) VALUES ('Clean Code', 'Read for Software Developer');
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION) VALUES ('Notebook Dell', 'I9 16bRAM');
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION) VALUES ('Notebook Lenovo', 'I7 8bRAM');
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION) VALUES ('Course Java', 'Specialist');
INSERT INTO TB_PRODUCTS (NAME, DESCRIPTION) VALUES ('Apple Watch', 'Smart Watch');